name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/$PROJECT_ID/my-app .
          docker push gcr.io/$PROJECT_ID/my-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-app --image gcr.io/$PROJECT_ID/my-app --platform managed --region us-central1 --allow-unauthenticated
